OP_SUCCESS = 10000

OP_BUILD_CONNECTION = 10001         #Build a new connection for new coming client
OP_BUILD_CONNECTION_SUCCESS = 100010
OP_BUILD_CONNECTION_FAILED = 100011

OP_REGISTER_APP = 10002
OP_REGISTER_SUCCESS = 100020
OP_REGISTER_FAILED = 100021

OP_UNREGISTER_APP = 10003
OP_UNRESIGTER_SUCCESS = 100030
OP_UNREGISTER_FAILED = 100031

OP_FAILED = 10010
OP_DISCONNECTED = 10011
OP_CONNECTION_BROKEN = 10012

OP_TRANSMIT_DATA = 10099



DES_SUCCESS = 'success'

DES_FAILED = 'failed'
DES_DISCONNECTED = 'socket_disconnected'

DES_TRANSMIT_DATA = 'transmit_data'

DES_BUILD_CONNECTION = 'build_connection'
DES_BUILD_CONNECTION_SUCCESS = 'build_connection_success'
DES_BUILD_CONNECTION_FAILED = 'build_connection_failed'

DES_REGISTER_APP = 'register_app'
DES_REGISTER_SUCCESS = 'register_success'
DES_REGISTER_FAILED = 'register_failed'

DES_UNREGISTER_APP = 'unregister_app'
DES_UNRESIGTER_SUCCESS = 'unregister_success'
DES_UNREGISTER_FAILED = 'unregister_failed'