OP_SUCCESS = 10000
OP_BUILD_CONNECTION = 10001         #Build a new connection for new coming client
OP_REGISTER_APP = 10002
OP_REGISTER_SUCCESS = 100020
OP_REGISTER_FAILED = 100021

OP_FAILED = 10010
OP_DISCONNECTED = 10011
OP_CONNECTION_BROKEN = 10012

OP_TRANSMIT_DATA = 10099

OP_REGISTER_APP = 10100



DES_SUCCESS = 'success'
DES_BUILD_CONNECTION = 'build_connection'
DES_FAILED = 'failed'
DES_DISCONNECTED = 'socket_disconnected'

DES_TRANSMIT_DATA = 'transmit_data'

DES_REGISTER_APP = 'register_app'
DES_REGISTER_SUCCESS = 'register_success'
DES_REGISTER_FAILED = 'register_failed'